### ISSUE TITLE
検索バーがない

### ISSUE THREAD

**Issue by taro04** [UnUniFi/utils#174]
telescope
![image](https://user-images.githubusercontent.com/75844498/147472544-b9537f2a-af09-43e9-9fc1-a0f98b22d5c4.png)
telescope-extention
![image](https://user-images.githubusercontent.com/75844498/147472565-71781df0-fa22-45e9-9eff-4f0d667ad6c9.png)

**Comment by YasunoriMATSUOKA** [comment]
対応完了したと思うのでクローズしておきます。
