### ISSUE TITLE
The Deposit Collateral step is wrong

### ISSUE THREAD

**Issue by chen981004** [UnUniFi/utils#192]
After completing the steps, the web page pops up with TxHash that needs to be recorded, and I made a record...  However, there is no record of this step when you look it up in your personal account (all other steps are there)

**Comment by YasunoriMATSUOKA** [comment]
@chen981004 
Thank you for creating the issue and sorry for the late replay.

Today, I tried all AirDrop tasks, and all the transactions were able to run as shown below, and the account information screen also showed those transactions as shown in the attached screenshot.

Are you still experiencing any problems? If you are still having problems, it would be helpful if you could provide more information.

Thank you for your patience.

| tx | tx hash |
| -------------------- | ---------------------------------------------------------------- |
| create cdp | [E9DE3D45DD252215E2BB1BE826697E58A29F9CBD41648616C679F7AD92B6C16B](http://a.test.ununifi.cauchye.net/txs/E9DE3D45DD252215E2BB1BE826697E58A29F9CBD41648616C679F7AD92B6C16B) |
| deposit collateral | [6B9A9FCED35D9187830CCB3FDBADC10DF4175162C107E60FD2C65911081533C4](http://a.test.ununifi.cauchye.net/txs/6B9A9FCED35D9187830CCB3FDBADC10DF4175162C107E60FD2C65911081533C4) |
| withdraw collateral | [F93A8A0074120A80DAD29B9C12AB9571CC5807513AD564FE117BF610454C9B98](http://a.test.ununifi.cauchye.net/txs/F93A8A0074120A80DAD29B9C12AB9571CC5807513AD564FE117BF610454C9B98) |
| issue cdp | [58D7DFF88E20A322692F49674F137AEC51959715C1DBF77819B8B4EE804EE76D](http://a.test.ununifi.cauchye.net/txs/58D7DFF88E20A322692F49674F137AEC51959715C1DBF77819B8B4EE804EE76D) |
| clear cdp | [4A3F27D43869416DC89DEE39F3A161A614ABE7AEA38394C91CB426E9E28C9F86](http://a.test.ununifi.cauchye.net/txs/4A3F27D43869416DC89DEE39F3A161A614ABE7AEA38394C91CB426E9E28C9F86) |
| return coins to faucet | [8466AC63366BDCDB6C892963C7CA861C839A298C76B2A89255F6270F5DE48261](http://a.test.ununifi.cauchye.net/txs/8466AC63366BDCDB6C892963C7CA861C839A298C76B2A89255F6270F5DE48261) |

![image](https://user-images.githubusercontent.com/55148923/153369296-72e4e6e3-05c9-4358-a0b1-7ca4679295bd.png)

**Comment by YasunoriMATSUOKA** [comment]
No response, so I will close it.
If you have still any problems, please contact us again.
