### ISSUE TITLE
ユーザーフレンドリーなエラーメッセージの実装

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/utils#200]
**Is your feature request related to a problem? Please describe.**

CDPに関して以下のような原因でトランザクションを実行できない場合があるのですが、全てStatus Code 400 or 500的なエラーになってしまい、ユーザーにとって何が問題なのか伝えることができていない現状があります。

- 秘密鍵の入力ミス
- 担保率不足状態になるトランザクションの試行
- 残高不足
- 手数料不足

**Describe the solution you'd like**

フォームやサービス等で適切にバリデーションやエラー通知を行えるように修正したいという内容になります。(CDPだけでなくAuctionについても本質的には同様の問題がありそうですが、現時点ではAirDropタスクにはなっていないので、優先度は若干低いと思っています。)

**Describe alternatives you've considered**

**Additional context**

**Comment by KimuraYu45z** [comment]
秘密鍵の入力ミスに関しては、入力された秘密鍵から公開鍵を導出して、その公開鍵がindexedDBで管理しているそれと一致するかバリデーションする手続きを挟むことで、トランザクション送るまでもなく対処できそうだなと思いました。

**Comment by taiki-furu** [comment]
このIssueに関する進捗状況を知ることはできるでしょうか。

**Comment by taro04** [comment]
@taiki-furu 

おつかれさまです。
（このIssueの認識はなかったですが、）以下ＰＲで現在進めています。
[https://github.com/UnUniFi/utils/pull/207](https://github.com/UnUniFi/utils/pull/207)

・秘密鍵の入力ミス ⇒ スナックバーで通知。
・担保率不足状態になるトランザクションの試行 ⇒ CDPからデータ持ってきてバリデーション
・残高不足 ⇒ 所持数でバリデーション。
・手数料不足 ⇒ スナックバーで通知。

**Comment by YasunoriMATSUOKA** [comment]
Completed
