### ISSUE TITLE
telescope修正反映

### ISSUE THREAD

**Issue by taro04** [UnUniFi/utils#205]
**Is your feature request related to a problem? Please describe.**

以下telescopeの修正をutilsに展開する必要があるかと思います。

- [x] 1, 秘密鍵入力のバリデーション [https://github.com/CauchyE/telescope/pull/281](https://github.com/CauchyE/telescope/pull/281)
- [x] 2, スナックバー閉 [https://github.com/CauchyE/telescope/pull/283](https://github.com/CauchyE/telescope/pull/283) 
- [x] 3, 数値入力最大値バリデーション [https://github.com/CauchyE/telescope/pull/270](https://github.com/CauchyE/telescope/pull/270)
・以下PR中
- [x] 10, MatCardのタイトル下スペース削除[https://github.com/CauchyE/telescope/pull/298](https://github.com/CauchyE/telescope/pull/298)
- [x] 11, 小数点以下の表示修正[https://github.com/CauchyE/telescope/pull/299](https://github.com/CauchyE/telescope/pull/299)
- [x] 12, 秘密鍵をUint8Arrayで持つ [https://github.com/CauchyE/telescope/pull/290](https://github.com/CauchyE/telescope/pull/290)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YasunoriMATSUOKA** [comment]
Completed
