### ISSUE TITLE
update website for NFTFi

### ISSUE THREAD

**Issue by KimuraYu45z** [UnUniFi/utils#210]

**Comment by ThetaShis** [comment]
Be a validatorとApply validatorのボタンに関して、機能していないので、もうコメントアウトしていいと思います。

あと、WhitepaperとOnepageをこちらに差し替えお願いいたします。
[UnUniFi Whitepaper.pdf](https://github.com/UnUniFi/utils/files/8308869/UnUniFi.Whitepaper.pdf)
[UnUniFi OnePage.pdf](https://github.com/UnUniFi/utils/files/8308874/UnUniFi.OnePage.pdf)

**Comment by ThetaShis** [comment]
**文書変更に関して**

<img width="476" alt="screen_shot_2022-03-19_at_16 48 35" src="https://user-images.githubusercontent.com/37920657/159143640-11a2395f-8256-49ee-95dc-f1641dfdceb0.png">

Synthetic Assets pegged to JPY&EUR&USD or index, etc. on Cosmos Network.
→
Decentralized cross-chain NFT marketplace/ platform with auto DeFi yield


UnUniFi is a public blockchain protocol deploying synthetic
assets including a suite of crypto-backed decentralized
stablecoins and tokens pegged to index of tokens on
blockchain e.g. GameFi, Metaverse or NFT on Cosmos Network.
→
UnUniFi Protocol is a decentralized finance(DeFi) platform that provides tools and features that allow users to create a collateralized deposit position, to synthesize a number of assets pegged to legal currency using NFTs and cryptocurrencies as collateral. As long as your NFTs are pledged as collateral, some rewards will come in on their own through the automatic DeFi of the issued stablecoins. The mission is “Give all NFTs the opportunity to DeFi”.

**Comment by YasunoriMATSUOKA** [comment]
Completed
