### ISSUE TITLE
CDPページにdepositsが表示されない

### ISSUE THREAD

**Issue by taro04** [UnUniFi/utils#211]
**Describe the bug**
所持CDPのページにて、depositsが表示されない。
![image](https://user-images.githubusercontent.com/75844498/159119672-aba01448-e6d3-4a91-9229-27ff77fe6320.png)

**To Reproduce**
1. Go to CDP
[http://a.test.ununifi.cauchye.net/ununifi/cdp/cdps/ununifi15rayjhf56y0lajhr6wgeqw5srdagvu4m43dgpj/ubtc-a](http://a.test.ununifi.cauchye.net/ununifi/cdp/cdps/ununifi15rayjhf56y0lajhr6wgeqw5srdagvu4m43dgpj/ubtc-a)

**Expected behavior**
depositした履歴が表示される。
（createした段階だと1件、追加でdepositすると2件のような動作と想定。）

※ざっと見た感じコンポーネントの実装は問題なさそうなので、client-ts側？

**Comment by YasunoriMATSUOKA** [comment]
@taikiFurusyo 
This may be resolved with following PR. Can you debug with all cdp patterns?
https://github.com/UnUniFi/utils/pull/229
If they be created as expected, check folloing lists and reply me plz.

- [ ] ubtc-jpy
- [ ] ubtc-eur
- [ ] ueth-jpy
- [ ] ueth-eur
