### ISSUE TITLE
Query param and selected account

### ISSUE THREAD

**Issue by taro04** [UnUniFi/utils#226]
**Describe the bug**
-
If the query parameter of the URL does not match the selected account, it will be rejected by the authentication of the private key.

**To Reproduce**
-
1. Go to CDP
2. Click on 'deposit'
3. Pop up account select window
4. select other account
5. move Deposit page, enter amount & privatekey, then submit
6. error 

**Expected behavior**
-
Once you select an account, it doesn't change even if you change pages.(this is better because less operation )
Alternatively, change the query parameters when the account changes.

**Screenshots**
-
![image](https://user-images.githubusercontent.com/75844498/160133534-9d15349f-b6d0-4ac9-87a2-2b8630cde9d4.png)

**Desktop (please complete the following information):**
- 

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by YasunoriMATSUOKA** [comment]
This Issue should be handled in the web-apps portal.
