### ISSUE TITLE
Deposit collateral page

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/utils#234]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Senna46** [comment]
As well as #235 
Seems to be working perfectly.
Limit is also working.

![スクリーンショット 2022-03-30 160318](https://user-images.githubusercontent.com/29295263/160772633-d4a2cc31-f308-4a41-9da7-a9abb725c59a.png)

**Comment by YasunoriMATSUOKA** [comment]
Can you deposit successfully?
