### ISSUE TITLE
Withdraw collateral page

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/utils#235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Senna46** [comment]
Seems to be working perfectly.
Limit is also working.

![スクリーンショット 2022-03-30 155303](https://user-images.githubusercontent.com/29295263/160772108-7e5a3e9e-3d10-4a1e-8292-16834d1f64ba.png)
![スクリーンショット 2022-03-30 160434](https://user-images.githubusercontent.com/29295263/160772265-9740950f-b334-4366-8c8e-8181f375d9c0.png)

**Comment by YasunoriMATSUOKA** [comment]
Can you check withdraw limit?

**Comment by Senna46** [comment]
Withdrawals that exceeded the Limit were highlighted in Red and could not be executed.

**Comment by YasunoriMATSUOKA** [comment]
OK. Then it will be ok.
