### ISSUE TITLE
Issue cdp page

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/utils#236]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Senna46** [comment]
Denom is not entered.
Does not work now.
![スクリーンショット 2022-03-30 161210](https://user-images.githubusercontent.com/29295263/160773082-cb944d86-7063-438e-bf73-7a956f6de319.png)
