### ISSUE TITLE
Clear cdp page

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [UnUniFi/utils#237]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Senna46** [comment]
As well as #236
![スクリーンショット 2022-03-30 161148](https://user-images.githubusercontent.com/29295263/160773164-01dacc61-f459-447c-a243-93819cd60078.png)
